@startuml Fibonacci

start
:Read N;
:_X,X,F := 0;
while (1 <= i <= N, i++) is (yes)
    if (i = 1) is (yes) then 
        :F := 1;
        :X := F;
    else
        :F := _X + X;
        :_X := X;
        :X := F;
    endif 
endwhile
:Print F;
stop

@enduml